service: aws-node-crud-turnos
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1
  iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:*
            - ses:*
        Resource: '*'            

plugins:
 # - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

package:
  individually: true

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate:  true
    migrationFile:
      dir:  offline/migrations

functions:  
  createHorario:
    handler: src/endpoints/horarios.addHorarios
    events:
      - httpApi:
          path: /horarios
          method: post
  getHorarios:
    handler: src/endpoints/horarios.getHorarios
    events:
      - httpApi:
          path: /horarios
          method: get
  addReserva:
    handler: src/endpoints/reservas.addReserva
    events:
      - httpApi:
          path: /reservas
          method: post        
  getReservas:
    handler: src/endpoints/reservas.getReservas
    events:
      - httpApi:
          path: /reservas
          method: get 
  getReserva:
    handler: src/endpoints/reservas.getReserva
    events:
      - httpApi:
          path: /reservas/{id}
          method: get                      
  sendEmail:
        handler: src/endpoints/email.sendEmail
        events:
          - httpApi:
              path: /send-email
              method: POST
        
                    

resources: # CloudFormation template syntax
  Resources:
    HorariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HorariosTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    ReservasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ReservasTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH            
