service: aws-node-crud-turnos
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
      - Effect: Allow
        Action:
            - dynamodb:*
        Resource:
            - arn:aws:dynamodb:us-west-2:689680609969:table/HorariosTable           


functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createHorario:
    handler: src/horarios.addHorarios
    events:
      - httpApi:
          path: /horarios
          method: post
  getHorarios:
    handler: src/horarios.getHorarios
    events:
      - httpApi:
          path: /horarios
          method: get          
                    

resources: # CloudFormation template syntax
  Resources:
    HorariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HorariosTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
